# Generated by Django 5.1.3 on 2025-10-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('video', 'Video'), ('opinion', 'Share Opinion'), ('game', 'Game')], default='video', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('watch', 'Watch Video'), ('like', 'Like Video'), ('subscribe', 'Subscribe Channel'), ('question', 'Answer Question'), ('game', 'Play Game')], max_length=20),
        ),
    ]
