# Generated by Django 5.2.7 on 2025-10-24 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_is_email_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='cfa_value',
            new_name='usd_value',
        ),
        migrations.RenameField(
            model_name='taskcompletion',
            old_name='cfa_earned',
            new_name='usd_earned',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='amount_cfa',
            new_name='amount_usd',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='available_balance_cfa',
            new_name='available_balance_usd',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='total_earned_cfa',
            new_name='total_earned_usd',
        ),
    ]
