# Generated by Django 5.2.8 on 2025-11-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_influencerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerprofile',
            name='budget_limit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum budget the influencer can spend. 0 means unlimited.', max_digits=10),
        ),
    ]
